### ISSUE TITLE
Commiteth web: Fix Your Accont drop-down so it is not misplaced

### ISSUE THREAD

**Issue by asemiankevich** [status-im/commiteth#111]
### Description

*Type*: Bug

*Summary*: On https://openbounty.status.im:444/app page after I log in I want to call `My account` either to logout or to add payment details. Now the drop-down is misplaced.

#### Expected behavior
Please check Zeplin screen https://app.zeplin.io/project/59dd4d45719799b4220a2e49/screen/59dd4dae68893c5c8d1d64b0

![image](https://user-images.githubusercontent.com/28752642/32216336-d656c40e-be35-11e7-8a9f-04df058b3e14.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/32216382-eda973b8-be35-11e7-9cfc-c82d0835e1ec.png)

### Additional Information

* Browser: Chrome

**Comment by tpatja** [comment]
Fixed in master and develop
