### ISSUE TITLE
Commiteth web: Fix error message UI

### ISSUE THREAD

**Issue by asemiankevich** [status-im/commiteth#112]
### Description

*Type*: Bug

*Summary*: The error message is too ugly with the white corners. As well it is too long, we can make it nicely-looking pop-up , no need to have it stretched from edge to edge

#### Expected behavior
Even I dont have appropriate Zeplin mock we need to redesign this error message and make it user-friendly

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/32217534-547b987a-be39-11e7-8874-e3a5e900de0e.png)

### Reproduction
 try to enable a repo without eth address saved

### Additional Information

* Browser: Chrome

**Comment by tpatja** [comment]
Fixed in develop and master
