### ISSUE TITLE
Commiteth Welcome page: Github link leads to 404

### ISSUE THREAD

**Issue by asemiankevich** [status-im/commiteth#137]
### Description

*Type*: Bug

*Summary*: Fix Github link so I dont receive 404 when clicking it on the Welcome page

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/32287053-9aa9aeba-bf40-11e7-8653-c040faffeba4.png)

### Additional Information

* Browser: Chrome

**Comment by tpatja** [comment]
Fixed in `develop`
