### ISSUE TITLE
Setup Yellerapp

### ISSUE THREAD

**Issue by jarradh** [status-im/commiteth#14]
http://yellerapp.com/

**Comment by commiteth** [comment]
Current balance: 0.0000 ETH
![QR Code](https://commiteth.com/qr/status-im/commiteth/bounty/14/beb6529a73faffb0c06274243ae8f5c95eee51a4f41513cf2d7113d977f6a826/qr.png)
[https://commiteth.com](https://commiteth.com)

**Comment by tpatja** [comment]
Unfortunately, Yeller has been [shut down](http://yellerapp.com/posts/2016-08-21-yeller-is-closing-down.html). We should look at alternatives.

**Comment by jarradh** [comment]
It was literally just up a few days ago, lmao. I guess yet another reason we need decentralised apps

**Comment by tpatja** [comment]
Yeller is not an option anymore. Let's open a new issue if we decide to use something else, like Sentry, in the future.
