### ISSUE TITLE
"Balance" and "Tokens" values on GH issue comment don't match values in "Activity" tab when the bounty is paid 

### ISSUE THREAD

**Issue by churik** [status-im/commiteth#151]
### Description

*Type*: Bug

*Summary*: 
after payment bounty balance with 0.0002 ETH and 10 STN shows 0.0000 ETH and 10 SNT. It’s not consistent. Would expect or 0 for both ETH and SNT or initial values shown for both.

#### Expected behavior
1. 0.00 ETH and 0 tokens
or
2. match initial bounty value (in my case 0.0002 ETH, 10 SNT)  like in "Activity"
![status open bounty 2017-11-06 21-51-39](https://user-images.githubusercontent.com/4557972/32460928-007f43b2-c33d-11e7-953c-9161fd7b3c6d.png)

#### Actual behavior
0.0002 ETH and 0 STN
![1](https://user-images.githubusercontent.com/4557972/32461036-40142d08-c33d-11e7-8694-6dd65599bed4.png)

### Reproduction

- Open Status (0.0002 ETH, 10 SNT)
- Merge pull request 
- Confirm and complete bounty payment
- Open GH issue 9should be closed)
- Pay attention to Tokens and Balance values

### Additional Information
Used MetaMask chrome plugin.
GH issue reference: https://github.com/Chu127001/bounty_1/issues/1

* Browser: Chrome 62.0.3202.75
* Operating System: OS X Sierra 10.12.6

**Comment by annadanchenko** [comment]
version 3e7df13
Issue had both ETH and SNT. After bounty payout for issue  https://github.com/Org1Watson/RepoW2/issues/6 GH comment shows `0.0002 ETH` and `0.00 SNT`

```
Balance: 0.0002 ETH
Tokens: SNT: 0.00
Contract address: 0xe2cef89795849161545b26c1c1ba9bef4c8daf5e
Network: Testnet (Ropsten)
Paid to: annadanchenko
```

Expected: both ETH and SNT show amounts they had before payout to the winner. E.g. 0.0002 ETH and 20.00 SNT.

Note that activity feed shows correct amounts for both SNT and ETH
<img width="942" alt="screen shot 2017-11-07 at 15 33 03" src="https://user-images.githubusercontent.com/6584810/32498958-729b1a22-c3d1-11e7-9c22-8450cfca5884.png">

Current (wrong) state:
<img width="1162" alt="screen shot 2017-11-07 at 15 32 49" src="https://user-images.githubusercontent.com/6584810/32498981-80c16174-c3d1-11e7-9321-2fea8b23902f.png">
