### ISSUE TITLE
Activity feed should show claims with 'pending maintainer confirmation' status 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/commiteth#152]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Activity feed does not show claims with 'pending maintainer confirmation' status. So PR is merged, claim is waiting for confirmation, however it disappears from Activity on the SOB site, so winner/audience can't see the claim anymore. It's confusing, would be better to show all states of the claim in Activity, including "pending maintainer confirmation" state.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Claim in state 'pending maintainer confirmation' is shown in SOB site in Activity feed. 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Claim in state 'pending maintainer confirmation' disappears from activity feed, so winner and other visitors can't see it on the site.
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Create issue with bounty, submit PR that fixes it. Check that claim is shown in Activity 
- Merge PR, so bounty comment shows  'pending maintainer confirmation' status on the GH issue. Check Activity feed for this claim

**Comment by tpatja** [comment]
A basic UI mockup showing the contents would be helpful. Data we have: eth balance, token balances, winner, repo.
