### ISSUE TITLE
Ensure all DB tables have a created_at and modified_at column

### ISSUE THREAD

**Issue by oskarth** [status-im/commiteth#173]
### User Story

As a developer, I want `created_at` and `modified_at` present in each DB table so that I can easily see what happened when and do more fine grained analytics.

### Description

*Type*: Feature

*Summary*: Ensure all DB tables have a created_at and modified_at column, including migrations.

#### Expected behavior
`created_at` and `modified_at` columns for all tables with standard Postgresql ISO 8601 UTC timestamp type, including migrations and in all DB operations.

#### Actual behavior
Nothing right now.

### Additional info

Queries: https://github.com/status-im/commiteth/blob/develop/resources/sql/queries.sql
Migrations: https://github.com/status-im/commiteth/tree/develop/resources/migrations

Libraries: https://github.com/luminus-framework/conman and https://github.com/yogthos/migratus

**Comment by tpatja** [comment]
We currently have `issues.updated` which reflects the last modification time. I think it's enough to add `created_at`.

**Comment by oskarth** [comment]
@tpatja To me this is issue is about _all_ tables, and `modified_at` should be at DB layer, no?

**Comment by tpatja** [comment]
The just added `created_at` field in the issues table gets set to current UTC timestamp when we insert an issue. They get inserted when the bounty label is added, so this gives use the bounty creation time. Am I missing something?

**Comment by andytudhope** [comment]
I'd like to have a timestamp when the bounty is created, and one for when the bounty is awarded and confirmed. I agree with @oskarth that it might be better to generalise this at the DB level, but am happy to work with just those 2 timestamps in the `issues` table for now.
