### ISSUE TITLE
Estimate gas instead of hard-coding

### ISSUE THREAD

**Issue by tpatja** [status-im/commiteth#19]
Currently eth.core/send-transaction (used for contract deployments and multisig wallet operations) uses a hard-coded value for gas. We should make the gas value dynamic by using eth_estimateGas.

**Comment by commiteth** [comment]
Current balance: 0.0000 ETH
Contract address: 0xb5f2c4a582b6f691c7c8f1728e3396b386143fdb
![QR Code](https://commiteth.com/qr/status-im/commiteth/bounty/19/fcc4e36f872e788ee597e717bec26fd55dc4764145d50ac8ac87033a279edfba/qr.png)
[https://commiteth.com](https://commiteth.com)

**Comment by commiteth** [comment]
Current balance: 0.00000000
Contract address: 0x663fe88488456f5fdb66be78ba06def9237d3a58
![QR Code](https://commiteth.com/qr/status-im/commiteth/bounty/19/efda1b5e072a6fb50c253c0365fea581e0235c9b7dbe81cab824a4042b91d7ad/qr.png)
[https://commiteth.com](https://commiteth.com)

**Comment by commiteth** [comment]
![Contract deploying](http://91.145.77.247:3000/img/deploying_contract.png)
