### ISSUE TITLE
Spinner shown forever on manage bounties view after confirming payout

### ISSUE THREAD

**Issue by tpatja** [status-im/commiteth#31]
### Description

*Type*: Bug

*Summary*: After clicking on the `Confirm` button for bounty pending payout on manage bounties view, the button is meant go into an in progress state until the transaction is approved in the connected wallet.

#### Expected behavior
Button spinner not shown after transaction approved. Bounty issue shown in "Old claims" list with greyed out "Signed off" button.

#### Actual behavior
Button spinner shown even after transaction approved. Payout succeeds, so this is just a UI glitch.

### Reproduction

* Pre-conditions:
    * user with admin access to a repo with bounties signed in
    * a bounty issue with a merged pull-request exists

- open "Bounties" page
- click on "Confirm"

### Additional Information
* Observed with MetaMask. Most likely happens with all wallets.

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
