### ISSUE TITLE
Organisations are not listed.

### ISSUE THREAD

**Issue by jarradh** [status-im/commiteth#33]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to add a repository from my organisation so that I can use commieth.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I want to add my organisation repository, like I used to.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
After signing in I want to goto repositories tab and 

#### Actual behavior
[comment]: # (Describe what actually happened.)
Nothing, I can only see personal.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Commiteth
- Sign-in
- Navigate to Repositories Tab
- See absolutely no organisation repositories

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by tpatja** [comment]
Fixed. UX will be improved in #35
