### ISSUE TITLE
Progressive permissioning

### ISSUE THREAD

**Issue by tpatja** [status-im/commiteth#35]
### User Story

As a user, I only want to grant commiteth permissions that are needed.

### Description

*Type*: Feature

*Summary*: Require only basic permissions when signing up and ask for more permissions when needed.

### Solution

* require only `user:email` when signing up 
* require additionally `admin:repo_hook`,  `repo` and `admin:org_hook` in case the user wants to use the Manage repositories feature (to be a repo admin). This can work so that if the user does not already have the full permission set, there is a button on the "Repositories" tab for granting access.

**Comment by Sija** [comment]
I was off put by requirement for an extended attributes (private repos), and especially giving an admin access. Perhaps some information beforehand why it's needed would help to mitigate the experience, still progressive permissioning seems like a better choice.

**Comment by jarradh** [comment]
We removed it, but then none of the organisation repositories were displayed and was forced to add it back in here https://github.com/status-im/commiteth/commit/a9b6a28dec799d7c2b9b3118a2bf0877b0d2288b 

Any ideas?

**Comment by tpatja** [comment]
Without the `repos` oauth scope, it is not possible to access *any* repository data (organization or private). This is a flaw in Github's oauth permissioning scheme (they should have a scope for read-only repository data) and there is an open ticket about it at their end. For now, the best we can do IMO is progressive permissioning, as described in this issue.

**Comment by Sija** [comment]
That's weird, [wafflo.io](https://waffle.io) manages somehow without it.
