### ISSUE TITLE
Way to see outstanding bounties

### ISSUE THREAD

**Issue by steveklebanoff** [status-im/commiteth#37]
### User Story

As a user, I want to see a list of outstanding bounties so that I can know where to contribute and earn some sweet ETH.

### Description

*Type*: Feature

*Summary*: Add ability to view a list of outstanding bounties.   

### Solution
I would expect that a new tab would be available labeled "Outstanding Bounties", next to "Activity".  This would list all outstanding bounty and link to issues.

**Comment by tpatja** [comment]
A tab listing open bounties is a good idea IMO.

**Comment by jarradh** [comment]
Agreed

**Comment by tpatja** [comment]
Now there is a simple "Open bounties" tab. Keeping ticket open, since UX may change.

**Comment by tpatja** [comment]
Feature implemented, closing
