### ISSUE TITLE
Layout looks broken on mobile browser and on status.im

### ISSUE THREAD

**Issue by flexsurfer** [status-im/commiteth#50]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description
Layout looks broken on mobile browser and on status.im

![image](https://cloud.githubusercontent.com/assets/11790366/24589043/aa4b3a52-17dc-11e7-96da-b3663762f5f5.png)

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Browser and version)
* Browser: Status.im

[comment]: # (OS version)
* Operating System: Status.im

**Comment by tpatja** [comment]
Thanks for the finding. I suppose the rendering is broken on both iOS and Android? Is it broken also in landscape mode or only portrait?

**Comment by flexsurfer** [comment]
i think on both, and on desktop it's easy to reproduce just need to reduce the size of the window. But on mobile in  landscape and portrait there is unnecessary horizontal scroll and white vertical field

**Comment by tpatja** [comment]
Old issue, not relevant to current UX
