### ISSUE TITLE
README.md downloads on site

### ISSUE THREAD

**Issue by frankcash** [status-im/commiteth#55]
### User Story

As a user of commiteth.com I went to commiteth.com/README.md and a README downloaded.

### Description

Bug

#### Expected behavior

A 404 page would be served

#### Actual behavior

A file downloaded

### Reproduction

- Go to commiteth.com/README.md

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:

### Additional Information
I was using chrome.

[comment]: # (Browser and version)
```
Built by Status
version d6aaa2d
```

### ETH Address
```0x4f22Fc7990F1a99133e5FAa40C4CD1De23a8e3C5```

![screen shot 2017-04-12 at 9 34 23 pm](https://cloud.githubusercontent.com/assets/6012231/24986368/d6c69a52-1fc7-11e7-918e-444a22aa012e.png)

**Comment by tpatja** [comment]
Thanks @frankcash, good catch!
Looks like the reagent dependency is putting it's readme in the uberjar.

**Comment by frankcash** [comment]
Glad I could help :)
