### ISSUE TITLE
Contract deployments sometimes run out of gas

### ISSUE THREAD

**Issue by tpatja** [status-im/commiteth#62]
### Description

With the new multisig, contract deployments are sometimes failing due to gas running out. It seems `estimate-gas` is not reliably returning large enough values.

Some examples:
https://etherscan.io/tx/0x1539a0f05352e43e8fb67d7a713c7f87891b5b36ba6d396309357ea96e82e660
https://etherscan.io/tx/0xc2e041c08662a1a5b3739a2d659208dcc58b8e145717779b524c07442438fdd4

**Comment by 3esmit** [comment]
if geth is having issues estimating gas than we need to fix a gas amount.
We know the gas needed so we can fix limit securely.
