### ISSUE TITLE
Support ERC20 using DSMultsig, DSAuth & DSAuthority

### ISSUE THREAD

**Issue by jarradh** [status-im/commiteth#7]
This is the Multisig contract used by Maker

https://github.com/nexusdev/ds-multisig
https://github.com/nexusdev/ds-auth/blob/master/src/DSAuthority50.sol
https://github.com/nexusdev/ds-auth/blob/master/src/auth.sol

> you will want to learn the DSAuthority pattern, which is what allows an ERC20 contract to have restricted access to only a multisig

> if you make your ERC20 contract inherit from DSAuth, then you can control it with a DSAuthority which is in turn owned by your multisig.

**Comment by 3esmit** [comment]
I've looked into this contracts and seems like overcomplicated and I didn't fit well the usecase. Can we consider closing this as we are going to use other solutions?

**Comment by tpatja** [comment]
Contracts for ERC20 support are written by @3esmit and live under `contracts/*.sol`
