### ISSUE TITLE
https://www.commiteth.com/ gives SSL error. 

### ISSUE THREAD

**Issue by 3esmit** [status-im/commiteth#74]

**Comment by tpatja** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=commiteth.com&latest

^no issues with ssl certificate. It will expire July 5th, but there is automation in place that will update it before.

**Comment by tpatja** [comment]
When using `https://www.commiteth.com` instead of `https://commiteth.com` there is a hostname mismatch. This can be fixed by redirecting the www to commiteth.com.

**Comment by 3esmit** [comment]
![image](https://user-images.githubusercontent.com/224810/27757943-8a1c1c76-5ddf-11e7-8138-36963ff72717.png)

**Comment by tpatja** [comment]
No known issues with SSL cert
