### ISSUE TITLE
Build system support for solidity

### ISSUE THREAD

**Issue by tpatja** [status-im/commiteth#80]
### Description

We currently have the bounty contract as a compiled binary file in Git. Let's have the solidity code in Git instead and make the Leiningen build compile it.

**Comment by 3esmit** [comment]
We should use truffle migrate to build the files and read what are the address from the truffle migration.

**Comment by tpatja** [comment]
Done. Uses solc and web3j from `$PATH`. Deploying of long lived contracts still needs to be done manually. If we decide to auto-deploy those to the blockchain as part of the build, let's create another ticket for that.
