### ISSUE TITLE
Move testnet version to Ropsten

### ISSUE THREAD

**Issue by tpatja** [status-im/commiteth#97]
Currently, our test deployment (where `develop` branch is automatically deployed to) uses Rinkeby as the testnet. We should change it to use latest Ropsten fork (Byzantium). This is important because we want Status-react to be on the same testnet.

**Comment by 3esmit** [comment]
https://ropsten.etherscan.io/address/0x3b9a3c062bdb640b5039c0ccda4157737d732f95#code <- New Factory Address - deployed in rinkeby and ropsten,

This address should be updated from old ~0x47F56FD26EEeCda4FdF5DB5843De1fe75D2A64A6~  to new *0x3B9A3c062Bdb640b5039C0cCda4157737d732F95* in multisig_wallet.clj#32 ( https://github.com/status-im/commiteth/blob/develop/src/clj/commiteth/eth/multisig_wallet.clj#L32 )

https://ropsten.etherscan.io/address/0xc0FFeEE61948d8993864a73a099c0E38D887d3F4#code <- Hardcoded address inside of stub (the library contract), deployed in rinkeby and ropsten

**Comment by 3esmit** [comment]
Ropsten Contracts:
- STT (Status Test Token): https://ropsten.etherscan.io/token/0xc55cf4b03948d7ebc8b9e8bad92643703811d162#balances
Exact same sourcecode of Mainnet SNT (MiniMeToken) 
- SNTPlaceHolder: https://ropsten.etherscan.io/address/0x34358C45FbA99ef9b78cB501584E8cBFa6f85Cef
Modified contract to be STT faucet. Send 0 ether (fallback function) to generate 1000 test STT. 
- TokenReg: https://ropsten.etherscan.io/address/0x7d127a3e3b5e72cd8f15e7dee650abe4fcced2b9#readContract
Already registered STT as SNT.
- Test Token 1: https://ropsten.etherscan.io/token/0x0fa211adf6f6d506cde88abf6832d226f7db73ad
Registered as GNT, can be minted by sending 0 ether to the token contract address (fallback function)

**Comment by tpatja** [comment]
> This address should be updated from old 0x47F56FD26EEeCda4FdF5DB5843De1fe75D2A64A6 to new 0x3B9A3c062Bdb640b5039C0cCda4157737d732F95 in multisig_wallet.clj#32 ( https://github.com/status-im/commiteth/blob/develop/src/clj/commiteth/eth/multisig_wallet.clj#L32 )

The address is taken from the config. 0x47F56FD26EEeCda4FdF5DB5843De1fe75D2A64A6 is just a fallback value in case no value exists in config or environment.

Please deploy the token registry contract to Ropsten and populate it with data of these test ERC20 token contracts.

**Comment by 3esmit** [comment]
TokenReg: https://ropsten.etherscan.io/address/0x7d127a3e3b5e72cd8f15e7dee650abe4fcced2b9#readContract

Contains 2 tokens registered:

STT (Status Test Token): https://ropsten.etherscan.io/token/0xc55cf4b03948d7ebc8b9e8bad92643703811d162#balances

Test Token 1: https://ropsten.etherscan.io/token/0x0fa211adf6f6d506cde88abf6832d226f7db73ad
Registered as GNT, can be minted by sending 0 ether to the token contract address (fallback function)

**Comment by tpatja** [comment]
The move resulted in bounty contract deployments breaking due to geth 1.7.0 giving too small gas estimates. This has now been fixed (fixed gas-limit for contract deployment + possibility define a global adjustment factor gas estimates) and the test environment at https://commiteth.com:444 is running on Ropsten.
